name: Deploy to EC2  # 이 워크플로우의 이름. GitHub Actions 탭에 표시됨

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때만 이 워크플로우가 실행됨

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions가 사용하는 가상 머신 환경 (우분투 최신 버전)
    env:
      AWS_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # 현재 저장소의 코드를 가져옴 (필수 단계)

      - name: Set up JDK
        uses: actions/setup-java@v4  # Java 빌드 환경을 설정함
        with:
          distribution: 'temurin'
          java-version: '21'  # Java 21 버전을 사용함 (Dockerfile과 일치해야 함)

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build -x test  # Gradle로 프로젝트를 빌드함. 테스트는 제외 (-x test)

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1  # ECR에 로그인. 이후 Docker push를 하기 위함
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=656697807760.dkr.ecr.ap-northeast-2.amazonaws.com/my-backend-repo:latest
          docker build -t $IMAGE_URI .  
          docker push $IMAGE_URI

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cat <<EOF > .env
            SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
            EOF
            docker stop app || true && docker rm app || true
            docker pull 656697807760.dkr.ecr.ap-northeast-2.amazonaws.com/my-backend-repo:latest
            docker run -d \
              --name app \
              --env-file .env \
              --network host \ 
              -p 8080:8080 \
              656697807760.dkr.ecr.ap-northeast-2.amazonaws.com/my-backend-repo:latest
